# Base configs
baseurl: "http://photagestudio.com"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-142568509-1"

# UI configs
title: "Photage Studio"
subtitle: "Commercial Photography"
author: "Photage Studio"
header:
 title: "Photage Studio"
 subtitle: "Commercial Photography"
footer:
 name: "Hey there, we're Photage"
 bio: "Photage is an Ottawa-based product photography studio that offers sharp, high-resolution, color-accurate product photo of Apparel, Jewelry, Cosmetics, Watches, Bags, Shoes and all types of Accessories for Online Stores to increase their sales and decrease order returns."
web_design: "<a href=\"https://intellity.ca\">Intellity</a> "
social_urls:
  facebook: "https://www.facebook.com/PhotageStudio"
  twitter: "https://www.twitter.com/PhotageStudio"
  instagram: "https://www.instagram.com/PhotageStudio"
  linkedin: "https://in.linkedin.com/company/PhotageStudio/"
